
# Project: Sales Data 
# 
# The dataset contains information about sales transactions, 
# including details such as the customer's age, gender, location, and the products sold.


# The quantity column provides information on the volume of products sold, 
# which could be used to analyze sales trends over time.
# The dataset includes information on customer age and gender, 
# which could be used to analyze purchasing behavior across different demographic groups.
# The dataset likely includes both numeric and categorical data, 
# which would require different types of analysis and visualization techniques.
# Overall, the dataset appears to provide a comprehensive view of sales transactions, 
# with the potential for analysis at multiple levels, including by product, customer, and location.



#Description of Columns: 
  
# Year: This column represents the year in which the transaction occurred. 
# 
# Month: This column represents the month in which the transaction occurred. 
# 
# Customer Age: This column represents the age of the customer. 
# 
# Customer Gender: This column represents the gender of the customer. 
# 
# Country: This column represents the country where the transaction occurred. 
# 
# State: This column represents the state where the transaction occurred. 
# 
# Product Category: This column represents the broad category of the product sold. 
# 
# Sub Category: This column represents the specific subcategory of the product sold. 
# 
# Quantity: This column represents the quantity of the product sold. 
# It could be used to analyze sales volume or to calculate the total revenue generated 
# from a particular product or product category.
# 
# Unit Cost: This column represents the cost of producing or acquiring one unit of the product. 
# 
# Unit Price: This column represents the price at which one unit of the product was sold. 
# 
# Cost: This column represents the total cost of the products sold, 
# which is calculated as the product of the quantity and the unit cost. 
# 
# Revenue: This column represents the total revenue generated by the sales, 
# which is calculated as the product of the quantity and the unit price.

# Profit: Revenue-Cost
# Proft_margin: Profit/Revenue


# The dataset contains 17 columns and 34,867 Rows


# This project involves an analysis of a company's sales for the years 2015 and 2016. 
# The company offers bikes, bike gear, and accessories in four different countries: 
# the US, Germany, France, and the UK. Through various metrics, the analysis aims 
# to gain insight into the company's revenue streams. The metrics include profitability, 
# top-selling products, and the most lucrative markets by country and state. 
# In addition, the project also looks into the demographics of the company's customer 
# base to better understand their shopping behavior.



# Beginning

packages <- c("DescTools","dplyr","ggplot2","readr","stringr","tidyr","visdat")
lapply(packages,require,character.only=T)

df = read.csv('salesforcourse-4fe2kehu.csv')
install.packages('scales')
library(scales)
library(kableExtra)
library(knitr)
vis_miss(df)

df$Column1 = NULL

df$Profit = df$Revenue-df$Cost
df$Profit_margin = (df$Profit/df$Revenue)*100

# I calculated a Profit column from the Revenue and Cost columns and the Profit Margins. 
# The data has no missing data except one column, which I removed. 

str(df)
df$Date <- as.Date(df$Date, "%m/%d/%Y")
table(df$Country)
df = df %>% filter(Country !='')

theme_s = theme(text = element_text(family='serif',size=14),
                axis.line = element_line(color='black'),
                title = element_text(color='#8b0000'),
                rect = element_blank(),
                panel.grid= element_blank())

# Company Stats 

company=df %>% summarize(total_transaction=n(),
                 Total_revenue = sum(Revenue),
                 Total_profit = sum(Profit),
                 Total_profit_margin = sum(Profit)/sum(Revenue)*100,
                 Total_quantity = sum(Quantity),
                 Avg_basket_size = sum(Revenue)/n())
                 
company





colnames(company) = c('Total Transaction','Total Revenue','Total Profit',
                      'Total Profit Margin(%)','Total Quantity','Average Basket Size')

kable(company,format='html',
      caption='Company Stats Lifetime') %>% 
  kable_styling(bootstrap_options = 'striped',full_width = T)


# The company's sales transaction count reached 34,866 in total.
# Throughout its existence, the company has generated approximately 22.34 million in revenue 
# and achieved a profit of around 2.26 million, resulting in a 10.12% profit margin.
# The company successfully sold 69,820 products in total, with an average basket size of 640 USD.

ggplot(df,aes(x=Unit.Price))+
  geom_histogram() +
  labs(title='Price Distribution of Products',
       y='Count',
       x='Unit Price (in USD)') +
  theme_s


# The presented graph illustrates the distribution of prices for the products.
# As shown, the distribution is skewed to the right, suggesting that some products were 
# considerably more expensive than the average product. Notably, the most expensive product 
# was sold for 5082 dollars.The average price for a product was 389 dollars, 
# whereas the median was 179 dollars. Furthermore, the most frequently occurring price was 17 dollars.
# It's worth noting that the range between the prices of different products was quite significant.

df %>% summarize(max = max(Unit.Price),
                            min = min(Unit.Price),
                            mean= mean(Unit.Price),
                            median=median(Unit.Price),
                            mode=Mode(Unit.Price),
                            sd = sd(Unit.Price))


# Country

ggplot(df,aes(x=Country)) + 
  geom_bar(fill='steelblue') + 
  theme_s + 
  labs(title= 'Number of Sales Transactions per Country',
       y='Count')

# Out of the four countries in our data set, the United States had the most significant 
# number of sales transactions, amounting to 18,076.The United Kingdom came in second with 6,421 transactions, 
# followed closely by Germany and France, with 5,201 and 5,186 transactions, respectively. 


country <- df %>% 
  group_by(Country) %>% 
  summarize(total_rev = sum(Revenue),
            total_profit = sum(Profit),
            total_profit_margin = sum(Profit)/sum(Revenue)*100,
            avg_basket_size = sum(Revenue) / n(),
            n = n())
country



ggplot(country,aes(x=Country,y=total_rev)) +
         geom_bar(stat='identity',fill='steelblue') + 
  theme_s + 
scale_y_continuous(breaks = c(0,2500000,5000000,7500000,10000000),label=c('0','2.5M','5.0M','7.5M','10M')) +
  labs(title='Lifetime Revenue by Country',
       y='Revenue (in USD)')

country
# In terms of lifetime sales, the United States leads with a figure exceeding 10 million USD.
# Germany and the United Kingdom trail behind with approximately 4.25 million in lifetime sales, 
# while France's lifetime revenue amounts to roughly 3.45 million.When analyzing sales on a per-country basis, 
# the United States emerges as the company's largest market.

ggplot(country,aes(x=Country,y=total_profit)) + 
  geom_bar(stat='identity',fill='steelblue') + 
  theme_s + 
  labs(title='Lifetime Profit by Country',
       y='Profit (in USD)') + 
  scale_y_continuous(breaks=c(0,250000,500000,750000,1000000),label = c('0','250K','500K','750K','1M'))


# Germany obtained the highest lifetime profits among the four countries, achieving roughly 960,000 USD.
# The United States follows as the second most profitable country, with profits of around 700,000 USD.





ggplot(country,aes(x=Country,y=avg_basket_size)) + 
  geom_bar(stat='identity',fill='steelblue') +
  theme_s  + 
  labs(title = 'Average Basket Size by Country',
       y='Average Basket Size (in USD) ') 

# Among the four countries, Germany displayed the highest lifetime average basket size, standing at 816 USD.
# France and the UK had similar average basket sizes, with both countries averaging around 666 USD per basket.
# The United States had the lowest average basket size at 574 USD.
# The average basket size was computed by dividing the total revenue by the number of 
# transactions for each respective country. 


ggplot(country,aes(x=Country,y=total_profit_margin)) + 
  geom_bar(stat='identity',fill='steelblue') +
  theme_s  + 
  labs(title = 'Total Profit Margin by Country',
       y='Total Profit Margin (in %)') 

# Out of the four countries in the dataset, Germany had by far the highest profit margin, reaching 22.6%. 
# This signifies that for every dollar earned in revenue, 22.6 cents were retained as profit.
# In contrast, the remaining three countries had more modest profit margins, ranging from 6.76% to 7.91%.

country1 = country %>% select(Country,Total_Revenue = total_rev,Total_Profit=total_profit,
                              Profit_margin_percent = total_profit_margin,
                              Average_basket_size= avg_basket_size,
                              Number_of_Transactions = n)

colnames(country1) = c('Country','Total Revenue','Total Profit','Profit Margin(%)',
                       'Average Basket Size','Sales Transaction Count')

kable(country1, format='html',
      caption= 'Descriptive Statistics by Country 2015 and 2016') %>%
  kable_styling(bootstrap_options = 'striped',full_width = F)




# Gender 

gender = df %>% group_by(Customer.Gender) %>% summarize(Total_Transaction = n(),
                                               Total_Revenue = sum(Revenue),
                                               Total_Profit = sum(Profit),
                                               Avg_Basekt_Size = sum(Revenue)/n(),
                                               Profit_Margin = sum(Profit)/sum(Revenue)*100)


colnames(gender) = c('Gender','Total Transaction','Total Revenue','Total Profit',
                     'Average Basket Size','Profit Margin(%)')
kable(gender,format='html',
      caption='Descriptive Statistics by Gender') %>%
  kable_styling(bootstrap_options = 'striped',full_width = T)




# Both genders have identical number of transactions at around 17,000 each.
# The total revenue, total profit and average basket size,total profit margins are almost identical.
# Both gender like to shop at the store and it seems the store has enough
# products to meet the demands of them. I didn't display the results, because it didn't make 
# much sense. 




# Product 

product=df %>% group_by(Product.Category) %>% summarize(Total_quantity= sum(Quantity),
                                                Total_Revenue = sum(Revenue),
                                                Total_Profit = sum(Profit),
                                                Total_Profit_Margin = sum(Profit)/sum(Revenue)*100,
                                                Avg_basket_size = sum(Revenue)/n(),
                                                Avg_Unit_Price = mean(Unit.Price),
                                                Number_Quantity = sum(Quantity))


product
ggplot(product,aes(x=Product.Category,y=Total_quantity)) + 
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Total Quantity sold by Product Category',
       x='Product Category',
       y= 'Quantity Sold') +
  theme_s

# The presented graph depicts the distribution of products sold by product category.
# According to the graph, the company sold approximately 45,048 accessory products, 
# 14,291 bikes, and 10,481 clothing items.


ggplot(product,aes(x=Product.Category,y=Total_Revenue)) + 
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Total Revenue by Product Category',
       x='Product Category',
       y= 'Total Revenue (in USD)') + 
  theme_s +
  scale_y_continuous(breaks = c(0,3000000,6000000,9000000,12000000),label=c('0','3M','6M','9M','12M'))

# The bike category was the biggest revenue generator for the company, bringing in approximately 11.5 million 
# in revenue.The accessories category followed closely behind, generating around 7.42 million in revenue.
# The clothing category was the smallest revenue generator, bringing in around 3.4 million in revenue.


ggplot(product,aes(x=Product.Category,y=Avg_Unit_Price)) + 
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Average Unit Cost by Product Category',
       x='Product Category',
       y= 'Average Unit Price (in USD)') + 
  theme_s

# The average cost of a product in the bikes category was approximately 982 USD for the customer.
# In the accessories category, the average cost of a product was around 200 USD for the customer.
# Finally, in the clothing category, the average cost of a product was approximately 400 USD for the customer. 


ggplot(product,aes(x=Product.Category,y=Total_Profit)) + 
  geom_bar(stat='identity',fill='steelblue') +
  labs(title=' Profit by Product Category ',
       x='Product Category',
       y= 'Profit (in USD)') + 
  scale_y_continuous(breaks= c(0,500000,1000000,1500000),labels= c('0','500K','1M','1.5M')) +
  theme_s


# The accessories category was the most profitable product category for the company, 
# generating approximately 1.3 million dollars in lifetime profits.
# On the other hand, the bikes category recorded the lowest lifetime profits, 
# bringing in around 337K for the company.


ggplot(product,aes(x=Product.Category,y=Total_Profit_Margin)) + 
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Total Profit Margin by Product Category ',
       x='Product Category',
       y= 'Profit Margin (in %)') +
  theme_s

# The bike Category had the lowest profit margins at only 2.94%, which indicates 
# that for every dollar earned in revenue the company only made 0.029 cents in revenue. 
# At this profit margins, it might not even make sense to sell products in the bike category,
# but we need to consider other factors before we can make an informed decision. 
# The Accessories and the Clothing category recorded profit margins at 18.5% and 15.87%, respectively.

product


# Sub Category 

sub=df %>% group_by(Sub.Category) %>% 
  summarize(total_revenue=sum(Revenue),
            total_profit = sum(Profit),
            total_profit_margin = sum(Profit)/sum(Revenue)*100,
            total_quantity = sum(Quantity))

sub

sub %>% arrange(desc(total_quantity)) %>% head(5) %>% 
  ggplot(aes(y=reorder(Sub.Category,+total_quantity),x=total_quantity))+ 
  geom_bar(stat='identity',fill='steelblue') + 
  labs(title='Top 5 Products with the Most Units Sold',
       x='Products',
       y='Units Sold') +
  theme_s

# The top 5 most sold products are Tires & Tubes, Bottles & Cages, Helmets, Road Bikes, and Mountain Bikes.
# Tires and Tubes are the most sold products, with close to 22,000 sales recorded.
# The company also sold 10,558 Bottles and Cages, 8,387 Helmets, 6,119 Road Bikes, and 5,499 Mountain Bikes.



sub %>% arrange(desc(total_revenue)) %>% head(5) %>% 
  ggplot(aes(x=reorder(Sub.Category,-total_revenue),y=total_revenue))+ 
  geom_bar(stat='identity',fill='steelblue') + 
  labs(title='Top 5 Products with the Highest Revenue',
       x='Products',
       y='Revenue (in USD)') + 
  scale_y_continuous(breaks= c(0,1000000,2000000,3000000,4000000,5000000),
                     label=c('0','1M','2M','3M','4M','5M')) +
  theme_s


# The Mountain Bikes category generated the highest revenue for the company, 
# with sales exceeding 5 million dollars. The Road Bikes category came in second, 
# generating around 3.9 million in revenue. The Tires and Tubes, Helmets, 
# and Touring Bikes categories completed the top five in terms of revenue.


sub %>% arrange(desc(total_profit)) %>% head(5) %>% 
  ggplot(aes(x=reorder(Sub.Category,-total_profit),y=total_profit))+ 
  geom_bar(stat='identity',fill='steelblue') + 
  labs(title='Top 5 Most Profitable Products in the Store',
       x='Products',
       y='Revenue (in USD)') +
  scale_y_continuous(breaks = c(0,100000,200000,300000,400000,500000),
                     labels= c('0','100K','200K','300K','400K','500K')) +
  theme_s 

# The graph displays the top 5 products with the highest profits generated by the company. 
# According to the graph, the most profitable product is Helmets, 
# which generated around 518K in profits. Tires and Lubes follow closely with around 512K in profits. 
# The other products that complete the top 5 are Jerseys, Mountain Bikes, and Bottles and Cages.

sub

sub %>% arrange(desc(total_profit_margin)) %>% head(5) %>% 
  ggplot(aes(x=reorder(Sub.Category,-total_profit_margin),y=total_profit_margin))+ 
  geom_bar(stat='identity',fill='steelblue') + 
  labs(title='Top 5 Products with the Highest Profit Margins',
       x='Products',
       y='Profit Margin in %')  +
  theme_s


# The highest profit margins among all products in the store are from Bike Racks, 
# which make 24.77% profit for every dollar earned in revenue. 
# Fenders, on the other hand, make the company  0.22 cents in profit for every dollar earned in revenue. 
# The top 5 products with the highest profit margins also include Gloves, Helmets, and Bottles and Cages. 




sub %>% arrange(total_profit_margin) %>% head(5) %>% 
  ggplot(aes(x=reorder(Sub.Category,+total_profit_margin),y=total_profit_margin))+ 
  geom_bar(stat='identity',fill='steelblue') + 
  labs(title='Bottom 5 Products with the Lowest Profit Margins',
       x='Products',
       y='Profit Margin %') +
  theme_s

# It appears that Road Bikes have the lowest profit margins among all products in the store, 
# with a margin of only 2.5%. Mountain Bikes and Touring Bikes also have relatively low profit margins, 
# indicating that the company does not make a lot of profit from the bikes category.




sub
sub %>% arrange(total_revenue) %>% head(5) %>% 
  ggplot(aes(x=reorder(Sub.Category,+total_revenue),y=total_revenue))+ 
  geom_bar(stat='identity',fill='steelblue') + 
  labs(title='Bottom 5 Products with the smallest Revenue generated',
       x='Products',
       y='Revenue (in USD) ')  + 
  theme_s 
  


# The graph displays the products with the lowest revenue.
# Socks brought the company only around 61K. Cleaners and Bike Racks generated
# the company around 82K and 140K, respectively. 


sub %>% arrange(total_profit) %>% head(5) %>% 
  ggplot(aes(x=reorder(Sub.Category,+total_profit),y=total_profit))+ 
  geom_bar(stat='identity',fill='steelblue') + 
  labs(title='Top 5 Products with the lowest profits',
       x='Products',
       y='Revenue in USD') +
  theme_s


# The graph depicts the five products with the lowest profit generated for the company. 
# Socks brought in a profit of only $9,500, while cleaners generated a profit of $14,664. 
# Bike stands were responsible for earning the company approximately $25,000 in profit.

df %>% group_by(Sub.Category) %>% summarize(max = max(Unit.Price)) %>% arrange(desc(max)) %>%
  head(5) %>%
  ggplot(aes(x=Sub.Category,y=max))+ 
  geom_bar(stat='identity') + 
  labs(title = 'Top 5 Highest Sales Transaction by Product',
       y='Sales Transaction ($)',
       x='Sub Category') +
  theme_s



# This graph shows the top 5 Products with the highest sales.
# A Bike Rack was sold for approximately 5,000 USD and a Mountain Bike for around 3,500 USD.
# Bike Racks are the most expensive products in the store.


# Seasonal changes 


month =df %>% group_by(Month) %>% summarize(total_transaction = n(),
                                     total_rev = sum(Revenue),
                                     total_profit= sum(Profit))
month %>% arrange(desc(total_transaction))


ggplot(month,aes(y=reorder(Month,total_transaction),x=total_transaction)) + 
  geom_bar(stat='identity') +
  labs(title = 'Number of Sales Transaction by Month',
       y='Month',
       x='Count') +
  theme_s

# In this data, the months of June and May had the highest number of recorded sales transactions, 
# reaching around 3,800 transactions. On the other hand, July and September had the 
# lowest recorded sales transactions, totaling just over each 2,000. 
# The sales transactions for all months in 2015 and 2016 were combined.


ggplot(month,aes(y=reorder(Month,total_rev),x=total_rev)) + 
  geom_bar(stat='identity') +
  labs(title = 'Total Revenue by Month',
       y='Month',
       x='in USD') + 
  scale_x_continuous(breaks= c(0,1000000,2000000),
                     labels= c('0','1M','2M'))

# According to the data, the months of June and May were the most successful in terms 
# of revenue generation for the company. In June, the company generated approximately 2.68 million in revenue, 
# while in May, it generated around 2.63 million. On the other hand, August, July, September, 
# and October were the worst-performing months, with the company generating approximately 1.25 million, 
# 1.28 million, 1.295 million, and 1.37 million in revenue, respectively.

ggplot(month,aes(y=reorder(Month,total_profit),x=total_profit)) + 
  geom_bar(stat='identity') +
  labs(title = 'Total Profit by Month',
       y='Month',
       x='Profit in USD') + 
  scale_x_continuous(breaks = c(0,100000,200000,300000),
                     labels= c('0','100K','200K','300K')) +
  theme_s

# The months of May and June were the most profitable for the company, while the period between 
# August and December saw the lowest profits. 
# In these months, the company generated less than $70,000 in profits each.



# Years


Years=df %>% group_by(Year) %>% summarize(total_transaction = n(),
                                    total_rev = sum(Revenue),
                                    total_profit= sum(Profit),
                                    total_profit_margin = sum(Profit)/sum(Revenue)*100)
Years
Years=t(Years)

Years = as.data.frame(Years)
Years

colnames(Years) = c('Year_one','Year_two')

Years = Years %>% slice(-1)
Years

Years = Years %>% mutate(change= (Year_two/Year_one-1)*100)
Years


library(tibble)
Years=rownames_to_column(Years, var = "Var")


ggplot(Years,aes(x=Var,y=change)) + 
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Yearly Performance of Key Business Metrics ',
       y=' Percentage Change  (%)',
       x='') + 
  scale_x_discrete(labels=c('Total_Profit','Total Profit Margin','Total Revenue','Total Transaction')) +
  theme_s
  
  
  
Years

# The graph depicts the percentage change in total profits, total profit margin, total revenue, 
# and total number of transactions between 2015 and 2016. The data shows that the company experienced 
# a substantial increase in their financial performance in 2016 compared to 2015. 
# Specifically, there was a 583% increase in total profits and a 448% increase in total profit margin. 
# Total revenue also increased by 24.6%, while the number of transactions went up by 32.15%. 
# These figures indicate that the company made significant improvements in their financial performance 
# over the year.


# Customers Age 




df$age_cat=cut(df$Customer.Age,breaks= c(0,18,30,45,60,Inf),
           labels= c('0-18','18-30','30-45','45-60','60+'))

df %>% select(Customer.Age,age_cat)






age=df %>% group_by(age_cat) %>% summarize(n=n(),
                                       total_rev = sum(Revenue),
                                       total_profit = sum(Profit),
                                       total_profit_margin = sum(Profit)/sum(Revenue)*100)

age
ggplot(age,aes(x=age_cat,y=n))+
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Age Distribution of Customers',
       y='Number of Customers',
       x='Age Category') +
  theme_s

# The largest age group among customers is composed of 30-45 year-olds, with a total of 15,749 individuals. 
# The second largest age group is made up of 18-30 year-olds, with a total of 11,033 customers. 
# The two age groups with the smallest number of customers are those under 18 years old and those 
# above 60 years old, with 808 and 804 customers, respectively.



ggplot(age,aes(x=age_cat,y=total_rev))+
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Total Revenue per Age Category',
       y='Count',
       x='Age Category') + 
  scale_y_continuous(breaks = c(0,3000000,6000000,9000000),
                     labels= c('0','3M','6M','9M'))


# The largest amount of revenue was generated by the 30-45 age group, 
# which amounted to slightly over $10.85 million. The age group of 18-30 year olds contributed around 
# $6.7 million in revenue to the company.


ggplot(age,aes(x=age_cat,y=total_profit))+
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Total Profit by Age Category',
       y='Total Profit ($)',
       x='Age Category') + 
  scale_y_continuous(breaks = c(0,300000,600000,900000),
                     labels= c('0','300K','600K','900K')) +
  theme_s


# The age group of 30-45 years old contributed more than 1.07 million dollars in profit to the company, 
# while the age group of 18-30 years old generated over 675,000 dollars in profit for the company.

ggplot(age,aes(x=age_cat,y=total_profit_margin))+
  geom_bar(stat='identity',fill='steelblue') +
  labs(title='Total Profit Margin by Age Category',
       y='Profit Margin %',
       x='Age Category') + 
  theme_s


# The graph shows the total profit margins of each age group. 
# The age group 0-18 had the highest total profit margin of 12.4%, 
# while the other age groups had profit margins ranging from 9.92% to 11.3%.


age1=df %>% group_by(age_cat) %>% summarize(n=n(),
                                       total_rev = sum(Revenue),
                                       total_profit = sum(Profit),
                                       total_profit_margin = sum(Profit)/sum(Revenue)*100)
colnames(age1) = c('Age Category','Number of Transactions','Total Revenue','Total Profit',
                  'Profit Margin(%)')
age1


kable(age1,format='html',
      caption = 'Descriptive Statistics by Age Group') %>%
  kable_styling(bootstrap_options = 'striped',full_width = F)



ggplot(df,aes(x=age_cat,y=Revenue))+
  geom_boxplot() + 
  labs(title = 'Age Category and Sales Transaction Distribution',
      y= 'Sales Transactions in USD',
      x='Age Category')  + 
  theme_s


# The boxplot provides a visual representation of the revenue distribution by age group. 
# Among the age categories, 30-45 has the highest median transaction amount at $381, 
# while the 0-18 and 18-30 age groups have similar median transaction amounts around $293.
# However, it's important to note that only a small fraction of the customer base is below 18 years old. 
# The highest transaction recorded was made by a person in the age group 45-60 for over $5000. 
# All age groups have a significant number of outliers on the upper end of the distribution. 
# The interquartile range, which measures the spread of the middle 50% of values, 
# is the largest for the 30-45 age group. Additionally, this age group has the greatest difference 
# between its mean and the data points.



df %>% group_by(age_cat) %>% summarize(n=n(),
                                       mean=mean(Revenue),
                                       median=median(Revenue),
                                       sd=sd(Revenue),
                                       max=max(Revenue),
                                       min= min(Revenue),
                                       iqr = IQR(Revenue),
                                       q1 = quantile(Revenue,0.25),
                                       q3 = quantile(Revenue,0.75))





df %>% group_by(age_cat,Product.Category) %>% summarize(n=sum(Quantity),
                                                        profit_margin=sum(Profit)/sum(Revenue)*100) %>% 
  slice_max(n,n=3) 

age_product=df %>% 
  group_by(age_cat, Product.Category) %>% 
  summarize(total_rev = sum(Revenue)) %>% 
  group_by(age_cat) %>% 
  mutate( percent_rev = total_rev / sum(total_rev) * 100,
          total_rev_by_age = sum(total_rev) )
age_product 
            

ggplot(age_product,aes(y=age_cat,x=percent_rev,fill=Product.Category)) + 
geom_bar(stat='identity',position='dodge') +
  labs(title='Spending habits of Age Groups',
       x='Percentage of Total Revenue in % ',
       y='Age Category')


# It seems that the graph represents the spending habits of different age groups. 
# The data shows that the 0-18 age group spent a total of around 3.73 million, 
# with the majority (46.3%) being spent on Accessories, followed by Bikes (31.6%) 
# and Clothing items (22.1%). On the other hand, the 30-45 age group spent over 10.8 million, 
# with the majority (53.8%) being spent on Bikes, followed by Accessories (31.2%) and Clothing items (15%).
# This data suggests that there is a significant difference in spending habits between the age groups. 










# State 

com=df %>% group_by(Country,State) %>% summarize(n=n(),
                                             total_rev = sum(Revenue),
                                             total_profit = sum(Profit),
                                             total_profit_margin = sum(Profit)/sum(Revenue)*100) 

com



ggplot(com,aes(y=reorder(State,+total_profit_margin),x=total_profit_margin,fill=Country)) +
  geom_bar(stat='identity',position='dodge') +
  labs(title = 'Profit Margins by State',
       x='Profit Margin in %',
       y='State') + 
  scale_x_continuous(breaks = c(-5,0,10,20)) +
  theme_s



# Germany is the most profitable market for the company, with the top 10 states with the 
# highest profit margins being dominated by German states. 
# The remaining four states in the top 10 are from the U.S. 
# Out of the five states with negative profit margins, four are from the U.S. and one is from France. .



df %>% group_by(Country,State) %>% summarize(n=n(),
                                             total_rev = sum(Revenue),
                                             total_profit = sum(Profit),
                                             total_profit_margin = sum(Profit)/sum(Revenue)*100) %>%
  arrange(desc(total_rev)) %>% head(15) %>% 
ggplot(aes(y=reorder(State,+total_rev),x=total_rev,fill=Country)) +
  geom_bar(stat='identity',position='dodge') +
  labs(title = 'Top 15 States with the Highest Revenue',
       x='Revenue in USD',
       y='State') + 
  scale_x_continuous(breaks = c(0,2000000,4000000,6000000),
                     labels=c('0','2M','4M','6M'))
 
# The graph shows the top 15 revenue-generating states for the company, 
# with California being the largest market, generating over 6 million dollars in revenue. 
# England, which is part of the UK, is the second largest market, 
# generating over 4.2 million dollars. Of the top 15 states,
# three are from the U.S. and all are in the top 4. The other top states are from Germany (5) and France (6).




df %>% group_by(Country,State) %>% summarize(n=n(),
                                             total_rev = sum(Revenue),
                                             total_profit = sum(Profit),
                                             total_profit_margin = sum(Profit)/sum(Revenue)*100) %>%
  arrange(desc(total_profit)) %>% head(15) %>% 
  ggplot(aes(y=reorder(State,+total_profit),x=total_profit,fill=Country)) +
  geom_bar(stat='identity',position='dodge') +
  labs(title = 'Top 15 States with the Highest Profit by Country',
       x='Profit in USD',
       y='State')  + 
  scale_x_continuous(breaks = c(0,100000,200000,300000,400000),
                     labels= c('0','100K','200K','300K','400K')) + theme_s
  
# California is the highest profit-generating state for the company, with over 393K in total lifetime profits. 
# England is a close second, generating 329K in profits. 
# Interestingly, only three U.S. states make it into the top 15 states with the highest profits, 
# while 5 German states, 6 states in France, and England (the only country in the UK) 
# make up the rest of the top 15.




df %>% group_by(Country,State) %>% summarize(n=n(),
                                             total_rev = sum(Revenue),
                                             total_profit = sum(Profit),
                                             total_profit_margin = sum(Profit)/sum(Revenue)*100) %>%
  arrange(desc(total_profit)) %>% head(15) %>% 
  ggplot(aes(y=reorder(State,+total_profit_margin),x=total_profit_margin,fill=Country)) +
  geom_bar(stat='identity',position='dodge') +
  labs(title = 'Top 15 States with the Highest Profit Margins',
       x='Profit Margin  (%)',
       y='State')  + 
  theme_s

# The graph shows the top 15 states with the highest profit margins, 
# with the top 5 spots being occupied by 5 German states. 
# All German states recorded a profit margin higher than 20%. 
# The remaining top 15 states consist of 3 states with comparatively 
# lower profit margins from the U.S., 6 states from France, and England.





# Compare why there's a difference in profitability between the U.S and Germany
#Product Category

ger_usa=df %>% filter(Country=='Germany' | Country == 'United States')

ger_usa=ger_usa %>% group_by(Country,Product.Category) %>% summarize(n=n(),
                                                     total_rev = sum(Revenue),
                                                     total_profit = sum(Profit),
                                                   total_profit_margin = sum(Profit)/sum(Revenue)*100,
                                                     total_quantity= sum(Quantity) )
ger_usa





ggplot(ger_usa,aes(x=Product.Category,y=total_profit,fill=Country)) + 
  geom_bar(stat='identity',position='dodge') +
  scale_y_continuous(breaks = c(-110000,0,200000,400000),
                     label = c('-110K','0','200K','400K')) +
  labs(title = 'Comparison of Total Profit by Product Category between Germany and USA',
       x='Product Category',
       y=' Profit in USD') + 
  theme_s


# The graph depicts the total profits made from each product category, 
# revealing that the U.S. recorded higher profits in the Accessories and Clothing categories,
# but experienced a loss of around 100K in the Bikes category. 
# In contrast, Germany recorded profits in all three product categories. 
# Of note, Germany generated over 400K in profits from the sales of its bikes, 
# which is particularly noteworthy.






ggplot(ger_usa,aes(x=Product.Category,y=total_profit_margin,fill=Country)) + 
  geom_bar(stat='identity',position='dodge')  +
  labs(title='Profit Margin by Product Category',
       y='Profit Margin  (%)',
       x='Product Category') + 
  scale_y_continuous(breaks = c(-3,0,10,20,30))+
  ylim(-10,40) + 
  theme_s
  

# The graph displays profit margins by product category for Germany and the U.S. 
# Notably, Germany recorded higher profit margins in all three product categories compared to the U.S. 
# In the Bikes category specifically, the U.S. lost around 2 cents for every dollar earned in revenue, 
# while Germany earned 16.9 cents in profits for every dollar earned in revenue from selling a bike. 
# These findings highlight the need to examine the specific products being sold in each country more closely.





ggplot(df,aes(x=Product.Category,y=Profit_margin)) +
  geom_boxplot() + 
  labs(title='Distiribution of Profit Margins by Product Category',
       y='Profit Margin (%)',
       x='Product Category') + 
  theme_s

# The boxplot reveals that, in general, the median profit margin for the Bikes category is close to zero, 
# while the median profit margins for Accessories and Clothing are around 17.2% and 15.6%, respectively. 
# Despite the low profitability of the Bikes category overall, the fact that Germany made 16.9 cents on 
# every dollar earned from the sale of a bike stands out as noteworthy.



df %>% group_by(Product.Category) %>% summarize(median = median(Profit_margin))




# Sub Category

sub.country=df %>% filter(Country =='Germany'| Country =='United States',Product.Category=='Bikes') %>%
  group_by(Country,Sub.Category) %>% summarize(mean_cost=mean(Unit.Cost),
                                               mean_price= mean(Unit.Price),
                                               mean_profit = mean(Profit),
                                               mean_profit_margin = mean(Profit)/mean(Revenue)*100)
sub.country1=df %>% filter(Country =='Germany'| Country =='United States',Product.Category=='Bikes') %>%
  group_by(Country,Sub.Category) %>% summarize(mean_cost=mean(Unit.Cost),
                                               mean_price= mean(Unit.Price),
                                               mean_profit = mean(Profit),
                                               mean_profit_margin = mean(Profit)/mean(Revenue)*100)


                                               
colnames(sub.country1) = c('Country','Sub Category','Average Cost',
                           'Average Price','Average Profit','Average Profit Margin')
kable(sub.country1,format='html',
    caption='Descriptive Statistics of the Bikes Category') %>%
kable_styling(bootstrap_options = 'striped',full_width = T)                         



ggplot(sub.country,aes(y=Sub.Category,x=mean_cost,fill=Country)) +
  geom_bar(stat='identity',position='dodge') + 
  labs(title= 'Analyzing Average Unit Costs of Bikes by Sub-Category and Country',
       y='Type',
       x=' Average Unit Cost($') + 
  theme_s

# The graph displays the average production costs of the three types of bikes that the company 
# is selling in Germany and the U.S. Notably, the average cost of producing a Touring bike is 
# higher in the U.S. than in Germany, while the average cost of producing a Road Bike is higher 
# in Germany than in the U.S. For Mountain Bikes, the average production cost is slightly 
# higher in Germany compared to the U.S. Despite these differences in production costs, 
# the data suggests that lower production costs in Germany are not the primary reason for 
# higher profit margins in the Bikes category. Therefore, there must be other factors at 
# play that contribute to the higher profit margins in Germany.
  
ggplot(sub.country,aes(y=Sub.Category,x=mean_price,fill=Country)) +
  geom_bar(stat='identity',position='dodge') + 
  labs(title= 'Comparison of Average Sale Price of Bikes by Sub-Category and Country',
       y='Type',
       x='Average Sale Price in USD')  + 
  theme_s

# The average selling price of all types of bikes is higher in Germany than in the U.S. 
# For instance, the average selling price of Mountain Bikes in Germany is 1406 dollars 
# while it is 1085 dollars in the U.S. By examining the average profit and profit margins, 
# we can understand the reason behind the Bikes Category's significantly higher profits 
# in Germany compared to the U.S. 



ggplot(sub.country,aes(y=Sub.Category,x=mean_profit,fill=Country)) +
  geom_bar(stat='identity',position='dodge') + 
  labs(title= 'Average Profit  of Bikes by Country',
       y='Type',
       x='Unit profit ($)') + 
  theme_s
 
# The provided data indicates that there is a significant difference in the profitability 
# of various types of bikes sold in Germany compared to the United States. 
# For instance, while a Mountain Bike generates an average profit of 404 dollars in Germany, 
# the company incurs a loss of 41.4 dollars for every unit sold in the United States.



ggplot(sub.country,aes(y=Sub.Category,x=mean_profit_margin,fill=Country)) +
  geom_bar(stat='identity',position='dodge') + 
  labs(title= 'Average Profit Margins of Bikes by Country',
       y='Type',
       x='Profit Margin (%)')  + 
  theme_s

# According to the data, the company achieves a positive average profit margin for all bike types 
# sold in Germany, while it reports a negative average profit margin for the same types of bikes 
# sold in the United States. 


country

# Conclusion: 
# Overall, the data suggests that the company has a strong presence in both the United States and Germany, 
# with these two countries accounting for a significant portion of the company's lifetime revenue and profit. 
# The company appears to have a diverse customer base with no significant differences in shopping behavior 
# between genders. The top-selling state is California, but the company has a strong presence in other states 
# in the US as well as the UK and Germany.
# The company seems to be implementing a different pricing strategy for bikes in the US and Germany, 
# with lower prices in the US resulting in higher sales volumes but lower profits compared to Germany, 
# where higher prices are charged resulting in lower sales volume but higher profits. Overall, 
# the company's strong financial performance in the US and Germany and diverse customer base suggest that it 
# is well-positioned for continued success in the future. 








